Repository 7th-UMC-Hackathon-TeamV/client, pull requests merged in 2025-01, with the labels that each got.

#6 feat: 폰트 컬러 세팅
  package-lock.json
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/onAirStyles.style.jsx
Labels: ✨ Feature

#12 feat: 이슈 템플릿 및 README.md 수정
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: 📄 Docs

#15 feat: news alert box 구현
  src/components/NewsAlertBox/NewsAlertBox.jsx
  src/components/NewsAlertBox/NewsAlertBox.style.jsx
  src/components/NewsAlertBox/index.js
  src/components/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#19 Feat/#18 hotnews card
  src/components/HotNewsCard.jsx
  src/components/HotNewsCard.style.js
Labels: ✨ Feature

#20 feat: 뉴스 헤더 컴포넌트 생성
  src/components/NewsHeader/NewsHeader.jsx
  src/components/NewsHeader/NewsHeader.style.jsx
  src/components/NewsHeader/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#33 modify: 홈화면 레이아웃 수정
  src/App.css
  src/components/HotNewsCard/HotNewsCard.jsx
  src/components/HotNewsCard/HotNewsCard.style.js
  src/components/HotNewsCard/index.js
  src/components/NewsCard/NewsCard.jsx
  src/components/NewsCard/NewsCard.style.js
  src/components/NewsCard/NewsCardList.js
  src/components/NewsCard/index.js
  src/components/NewsCardList/NewsCardList.js
  src/components/NewsCardList/NewsCardList.style.js
  src/components/NewsCardList/index.js
  src/components/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/styles/onAirStyles.style.jsx
Labels: 🛠️ Refactor, 🪄 Modify

#35 docs: PR 템플릿 내 이슈 번호 추가
  .github/pull_request_template.md
Labels: 📄 Docs

#37 feat: 링크 생성 페이지 제작
  package.json
  src/pages/StartPage/StartPage.jsx
  src/pages/StartPage/StartPage.style.js
  src/router.jsx
Labels: ✨ Feature

#39 feat: 홈 페이지 내 뉴스가 없을 경우 띄울 문구 추가
  src/components/HotNewsCard/HotNewsCard.jsx
  src/components/HotNewsCard/HotNewsCard.style.jsx
  src/components/NewsCard/NewsCard.style.jsx
  src/components/NewsCardList/NewsCardList.jsx
  src/components/NewsCardList/NewsCardList.style.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/styles/onAirStyles.style.jsx
Labels: ✨ Feature

#41 feat: 속보 스와이프 넘기기 구현
  package-lock.json
  package.json
  src/index.js
  src/pages/HomePage/HomePage.jsx
  src/svgs/onair_logo.svg
Labels: ✨ Feature

#44 feat: 로그인 타이틀에 컴포넌트 적용
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.style.jsx
Labels: ✨ Feature

#47 Feat/#42 logo header
  .env
  public/svgs/onair_logo.svg
  src/components/LogoHeader/LogoHeader.jsx
  src/components/LogoHeader/LogoHeader.style.js
  src/components/LogoHeader/index.js
  src/components/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/NewsPage/NewsPage.jsx
  src/pages/StartPage/StartPage.jsx
  src/pages/UpdateNewsPage/UpdateNewsPage.jsx
Labels: ✨ Feature

#49 chore: 홈 화면 컴포넌트 간격 수정
  src/components/NewsHeader/NewsHeader.style.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#54 feat: 홈화면 내 일부 컴포넌트 삭제 및 추가
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/LoginPage/LoginPage.jsx
Labels: ✨ Feature

#59 Design/#57 news component
  src/components/HotNewsCard/HotNewsCard.jsx
  src/components/HotNewsCard/HotNewsCard.style.jsx
  src/components/NewsCard/NewsCard.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.jsx
Labels: ✨ Feature

#61 fix: 배포 해결을 위한 파일 추가
  netlify.toml
  public/_redirects
  src/pages/LoginPage/LoginPage.jsx
Labels: 🔧 Fix

#63 merge: dev to main
  netlify.toml
  public/_redirects
  src/components/BottomBar/BottomBar.jsx
  src/components/HotNewsCard/HotNewsCard.jsx
  src/components/HotNewsCard/HotNewsCard.style.jsx
  src/components/NewsCard/NewsCard.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.jsx
Labels: 🌏 Deploy

#70 chore: 뉴스 사진 mock data 추가
  src/components/NewsCardList/NewsCardList.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 🎨 UI

#71 modify: ui 일부 수정
  src/components/BottomBar/BottomBar.style.jsx
  src/pages/LoginPage/LoginPage.style.jsx
  src/pages/StartPage/StartPage.jsx
  src/pages/StartPage/StartPage.style.js
Labels: 🎨 UI, 🪄 Modify

#74 fix: 버튼 너비 수정
  src/pages/StartPage/StartPage.style.js
Labels: 🔧 Fix

#82 chore: 마이페이지 더미데이터 카드 생성
  src/components/NewsCard/NewsCard.style.jsx
  src/pages/MyPage/MyPage.jsx
Labels: ✨ Feature

#88 chore: 속보 뉴스 디자인 수정
  src/components/HotNewsCard/HotNewsCard.style.jsx
  src/components/NewsCard/NewsCard.style.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 🎨 UI

#76 merge: dev to main
  src/components/BottomBar/BottomBar.jsx
  src/components/BottomBar/BottomBar.style.jsx
  src/components/HotNewsCard/HotNewsCard.jsx
  src/components/HotNewsCard/HotNewsCard.style.jsx
  src/components/NewsCard/NewsCard.jsx
  src/components/NewsCard/NewsCard.style.jsx
  src/components/NewsCardList/NewsCardList.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.style.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/NewsPage/NewsPage.jsx
  src/pages/NewsPage/NewsPage.style.jsx
  src/pages/StartPage/StartPage.jsx
  src/pages/StartPage/StartPage.style.js
Labels: 🌏 Deploy

#91 merge: dev to main
  package-lock.json
  package.json
  src/components/BottomBar/BottomBar.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/UpdateNewsPage/UpdateNewsPage.jsx
  src/pages/UpdateNewsPage/UpdateNewsPage.style.jsx
Labels: 🌏 Deploy
